apiVersion: v0.1
workloads:
  databroker:
    runtime: podman
    agent: agent_A
    runtimeConfig: |
      image: ghcr.io/eclipse/kuksa.val/databroker:0.4.1
      commandArgs:
        - "--insecure"
        - "--vss"
        - "/tmp/val.json"
      commandOptions:
        - "--net=host"
        - "-v"
        - "/home/chris/challengers/ankaios:/tmp"
  g29-publisher:
    runtime: podman
    agent: agent_B
    runtimeConfig: |
      image: docker.io/bleach31/g29-publisher:latest
      commandOptions:
        - "--net=host"
        - "--privileged"
#  vehicledashboard:
#    runtime: podman
#    agent: agent_A
#    runtimeConfig: |
#      image: docker.io/likhithst/vehicle_dashboard:latest
#      commandOptions:
#        - "--net=host"
#        - "-e"
#        - "BROKER_ADDRESS=192.168.1.99"
#        - "-e"
#        - "BROKER_PORT=55555"
#  drive-data-eval:
#    runtime: podman
#    agent: agent_A
#    runtimeConfig: |
#      image: {PLACE_TO_CONTAINER}
#      commandArgs: ["--insecure"]
#      commandOptions:
#        - "--net=host"
